services:
  # Service de l'application web PHP / Apache
  app:
    build: .
    container_name: facturation_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_NAME=${DOCKER_DB_NAME}
      - DB_USER=${DOCKER_DB_USER}
      - DB_PASS=${DOCKER_DB_PASS}
    depends_on:
      - db

  # Service de la base de données MySQL
  db:
    image: mysql:8.0
    container_name: facturation_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASS}
    ports:
      - "3307:3306" # Port 3307 externe pour éviter tout conflit avec MySQL local de Laragon (3306)
    volumes:
      - db_data:/var/lib/mysql
      # Chargement automatique du schéma SQL de départ
      - ./database/facturation.sql:/docker-entrypoint-initdb.d/init.sql

  # Service phpMyAdmin pour gérer facilement la base de données via une interface web
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: facturation_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DOCKER_DB_HOST}
      - PMA_USER=${DOCKER_DB_USER}
      - PMA_PASSWORD=${DOCKER_DB_PASS}
    depends_on:
      - db

volumes:
  db_data:
